### ISSUE TITLE
Remote Import Execution

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-client#22]
Hi @ralphhanna,

I am tring to execute remote import using the client. For some reason, it's not improting but no error too.

I have a BPMN file named `diagram.bpmn` in the folder `.workflows` of the working directory.

```
const { BPMNClient } = require("bpmn-client");
const path = require('path');

const dotenv = require("dotenv");
dotenv.config();


const server = new BPMNClient(
  process.env.HOST,
  process.env.PORT,
  process.env.API_KEY
);

const rootPath = '';
const workflowsPath = path.join(__dirname, '.workflows');

console.log(`workflowsPath: ${workflowsPath}`);

const dataPath = path.join(workflowsPath, 'diagram.bpmn');

console.log(`dataPath: ${dataPath}`);

server.definitions.import('RTPDummy', dataPath);
```

`bpmn-server` is running locally on port `3000`. `.env` is configured correctly.

**Cmd Output:**

![image](https://user-images.githubusercontent.com/55505611/210621590-b9e84afe-1970-4fbb-bb39-7ec7bf104082.png)

No Error. But the bpmn file is not imported into the server.

Could you please let me know what am I doing wrong?

**Comment by ralphhanna** [comment]
Sorry, Fixed in new release , please update
