### ISSUE TITLE
Client to suscribe to Service Tasks?

### ISSUE THREAD

**Issue by AgileEduLabs** [ralphhanna/bpmn-client#23]
Hi @ralphhanna ,

First, thanks for this wonderful package.

In "bpmn-server", there are several examples on how to implement a [Service Task](https://github.com/ralphhanna/bpmn-server/blob/master/docs/examples.md#service-task) in code using a custom MyAppDelegate.

In "bpmn-client", can we subscribe to a Service Task, and run code on the client when a Service Task needs to be run?

**Comment by ralphhanna** [comment]
Sorry for very late response. 
No, since the entire process runs on the server, the client should not intervene.
Instead you can run the process on the client!
