### ISSUE TITLE
Adding `vars` to the interface

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-client#26]
Hi @ralphhanna,

Could you please add `vars` to the interface `DataObjects.ts` as well?

Also, could you please make sure the changes reflect in the `npm` package as well; the [last PR](https://github.com/ralphhanna/bpmn-client/pull/25) isn't reflected in that?

Thank you!

**Comment by SundaramMaheshkumar** [comment]
Create a PR for this issue: https://github.com/ralphhanna/bpmn-client/pull/27
